/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.core

import dev.quadstingray.quartz.manager.client.model._
import io.circe.generic.AutoDerivation
import io.circe.Decoder
import io.circe.Encoder
import sttp.client3.circe.SttpCirceApi

object JsonSupport extends SttpCirceApi with AutoDerivation with DateSerializers with AdditionalTypeSerializers {

  implicit val StatusDecoder: Decoder[Status.Status] = Decoder.decodeEnumeration(Status)
  implicit val StatusEncoder: Encoder[Status.Status] = Encoder.encodeEnumeration(Status)
}
