/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.8.1-SNAPSHOT
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.api

import dev.quadstingray.quartz.manager.client.core.JsonSupport._
import dev.quadstingray.quartz.manager.client.model.ErrorResponse
import dev.quadstingray.quartz.manager.client.model.LogRecord
import dev.quadstingray.quartz.manager.TestAdditions
import sttp.client3._
import sttp.model.Method

object HistoryApi {
  def apply(baseUrl: String = TestAdditions.testServerHost) = new HistoryApi(baseUrl)
}

class HistoryApi(baseUrl: String) {

  /** Returns a single Job History record by its ID
    *
    * Expected answers: code 200 : LogRecord () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param id
    */
  def historyById(
    bearerToken: String,
    username: String,
    password: String
  )(id: String): Request[Either[ResponseException[String, Exception], LogRecord], Any] = {
    val request = basicRequest
      .method(Method.GET, uri"$baseUrl/api/history/${id}")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth.auth
      .basic(username, password)
      .response(asJson[LogRecord])
  }

  /** Returns the List of all Jobs History with full information
    *
    * Expected answers: code 200 : Seq[LogRecord] () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param query
    *   Lucene query string for filtering (e.g., 'jobGroup:batch AND className:MyJob')
    * @param sort
    *   Comma-separated sort fields, prefix with '-' for descending (e.g., '-date,className')
    */
  def historyList(bearerToken: String, username: String, password: String)(
    query: Option[String] = None,
    sort: Option[String] = None
  ): Request[Either[ResponseException[String, Exception], Seq[LogRecord]], Any] = {
    val request = basicRequest
      .method(Method.GET, uri"$baseUrl/api/history?query=${query}&sort=${sort}")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth.auth
      .basic(username, password)
      .response(asJson[Seq[LogRecord]])
  }
}
