/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.8.1-SNAPSHOT
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.api

import dev.quadstingray.quartz.manager.client.core.JsonSupport._
import dev.quadstingray.quartz.manager.client.model.ErrorResponse
import dev.quadstingray.quartz.manager.client.model.SchedulerInformation
import dev.quadstingray.quartz.manager.TestAdditions
import sttp.client3._
import sttp.model.Method

object SchedulerApi {
  def apply(baseUrl: String = TestAdditions.testServerHost) = new SchedulerApi(baseUrl)
}

class SchedulerApi(baseUrl: String) {

  /** Start the Quartz Scheduler
    *
    * Expected answers: code 200 : SchedulerInformation () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def schedulerInformation(bearerToken: String, username: String, password: String)(
  ): Request[Either[ResponseException[String, Exception], SchedulerInformation], Any] = {
    val request = basicRequest
      .method(Method.GET, uri"$baseUrl/api/scheduler")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth.auth
      .bearer(bearerToken)
      .auth
      .basic(username, password)
      .response(asJson[SchedulerInformation])
  }

  /** Shutdown the Quartz Scheduler
    *
    * Expected answers: code 204 : (Scheduler shutdown) code 400 : String (Invalid value for: query parameter waitForJobsToComplete) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param waitForJobsToComplete
    */
  def shutdownScheduler(bearerToken: String, username: String, password: String)(
    waitForJobsToComplete: Option[Boolean] = None
  ): Request[Either[ResponseException[String, Exception], Unit], Any] = {
    val request = basicRequest
      .method(Method.POST, uri"$baseUrl/api/scheduler/shutdown?waitForJobsToComplete=${waitForJobsToComplete}")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth.auth
      .basic(username, password)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )
  }

  /** Standby the Quartz Scheduler
    *
    * Expected answers: code 204 : (Scheduler standby) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def standbyScheduler(bearerToken: String, username: String, password: String)(
  ): Request[Either[ResponseException[String, Exception], Unit], Any] = {
    val request = basicRequest
      .method(Method.POST, uri"$baseUrl/api/scheduler/standby")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth.auth
      .basic(username, password)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )
  }

  /** Start the Quartz Scheduler
    *
    * Expected answers: code 204 : (Scheduler started) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def startScheduler(bearerToken: String, username: String, password: String)(
  ): Request[Either[ResponseException[String, Exception], Unit], Any] = {
    val request = basicRequest
      .method(Method.POST, uri"$baseUrl/api/scheduler/start")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth.auth
      .basic(username, password)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )
  }

}
