/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.8.1-SNAPSHOT
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.api

import dev.quadstingray.quartz.manager.client.core.JsonSupport._
import dev.quadstingray.quartz.manager.client.model.ErrorResponse
import dev.quadstingray.quartz.manager.client.model.Overview
import sttp.client3._
import sttp.model.Method

object SystemApi {
  def apply(baseUrl: String = "http://localhost") = new SystemApi(baseUrl)
}

class SystemApi(baseUrl: String) {

  /** Get all Information about the system and current quartz scheduler
    *
    * Expected answers: code 200 : Overview () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def systemOverview(bearerToken: String, username: String, password: String)(
  ): Request[Either[ResponseException[String, Exception], Overview], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/system")
      .contentType("application/json")
      .auth
      .bearer(bearerToken)
      .auth
      .basic(username, password)
      .response(asJson[Overview])

}
