/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.8.1-SNAPSHOT
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.model

import org.joda.time.DateTime

case class LogRecord(
  id: String,
  className: String,
  date: DateTime,
  logMessages: Option[Seq[LogMessage]] = None,
  jobGroup: Option[String] = None,
  jobName: Option[String] = None
)
