/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.model

import org.joda.time.DateTime

case class JobInformation(
  name: String,
  group: String,
  jobClassName: String,
  description: Option[String] = None,
  cronExpression: String,
  priority: Int,
  lastScheduledFireTime: Option[DateTime] = None,
  nextScheduledFireTime: Option[DateTime] = None,
  scheduleInformation: Option[String] = None
)
