/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.model

import dev.quadstingray.quartz.manager.client.model.Status._

case class SchedulerInformation(
  id: String,
  name: String,
  version: String,
  schedulerClass: String,
  jobStoreClass: String,
  status: Status,
  currentlyExecutingJobs: Int,
  threadPoolSize: Int
)

object SchedulerInformationEnums {}
