/**
 * quartz-manager-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package dev.quadstingray.quartz.manager.client.model



object Status extends Enumeration {
    type Status = Status.Value
    val Started = Value("Started")
    val Standby = Value("Standby")
    val Shutdown = Value("Shutdown")
    val Unknown = Value("Unknown")
}
