/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.api

import dev.quadstingray.quartz.manager.TestAdditions
import dev.quadstingray.quartz.manager.client.core.JsonSupport._
import dev.quadstingray.quartz.manager.client.model.ErrorResponse
import dev.quadstingray.quartz.manager.client.model.TokenResponse
import sttp.client3._
import sttp.model.Method

object AuthApi {
  def apply(baseUrl: String = TestAdditions.testServerHost) = new AuthApi(baseUrl)
}

class AuthApi(baseUrl: String) {

  /** Returns the token for the user to access the API
    *
    * Expected answers: code 200 : TokenResponse () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http)
    */
  def checkToken(bearerToken: String)(
  ): Request[Either[ResponseException[String, Exception], TokenResponse], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/auth/token")
      .contentType("application/json")
      .auth
      .bearer(bearerToken)
      .response(asJson[TokenResponse])

  /** Returns the token for the user to access the API
    *
    * Expected answers: code 200 : TokenResponse () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http)
    */
  def extendToken(bearerToken: String)(
  ): Request[Either[ResponseException[String, Exception], TokenResponse], Any] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/api/auth/token")
      .contentType("application/json")
      .auth
      .bearer(bearerToken)
      .response(asJson[TokenResponse])

  /** Returns the token for the user to access the API
    *
    * Expected answers: code 200 : TokenResponse () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth (http)
    */
  def login(username: String, password: String)(
  ): Request[Either[ResponseException[String, Exception], TokenResponse], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/auth/login")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .response(asJson[TokenResponse])

}
