/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.api

import dev.quadstingray.quartz.manager.TestAdditions
import dev.quadstingray.quartz.manager.client.core.JsonSupport._
import dev.quadstingray.quartz.manager.client.model.LogRecord
import sttp.client3._
import sttp.model.Method

object HistoryApi {
  def apply(baseUrl: String = TestAdditions.testServerHost) = new HistoryApi(baseUrl)
}

class HistoryApi(baseUrl: String) {

  /** Returns the List of all Jobs History with full information
    *
    * Expected answers: code 200 : Seq[LogRecord] ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def historyList(username: String, password: String, bearerToken: Option[String])(): Request[Either[ResponseException[String, Exception], Seq[LogRecord]], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/history")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .response(asJson[Seq[LogRecord]])

}
