/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.api

import dev.quadstingray.quartz.manager.client.core.JsonSupport._
import dev.quadstingray.quartz.manager.client.model.ErrorResponse
import dev.quadstingray.quartz.manager.client.model.JobConfig
import dev.quadstingray.quartz.manager.client.model.JobInformation
import dev.quadstingray.quartz.manager.client.model.TriggerConfig
import dev.quadstingray.quartz.manager.TestAdditions
import sttp.client3._
import sttp.model.Method

object JobsApi {
  def apply(baseUrl: String = TestAdditions.testServerHost) = new JobsApi(baseUrl)
}

class JobsApi(baseUrl: String) {

  /** Delete Job and reload all Job Information
    *
    * Expected answers: code 204 : (Job deleted) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param jobGroup
    *   Group Name of the Job
    * @param jobName
    *   Name of the Job
    */
  def deleteJob(bearerToken: String, username: String, password: String)(
    jobGroup: String,
    jobName: String
  ): Request[Either[ResponseException[String, Exception], Unit], Any] = {
    val request = basicRequest
      .method(Method.DELETE, uri"$baseUrl/api/jobs/${jobGroup}/${jobName}")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth
      .auth
      .basic(username, password)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )
  }

  /** Execute scheduled Job manually
    *
    * Expected answers: code 204 : (Job added to trigger) code 400 : String (Invalid value for: body) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param jobGroup
    *   Group Name of the Job
    * @param jobName
    *   Name of the Job
    * @param requestBody
    *   Job Data map
    */
  def executeJob(
    bearerToken: String,
    username: String,
    password: String
  )(jobGroup: String, jobName: String, requestBody: Map[String, String]): Request[Either[ResponseException[String, Exception], Unit], Any] = {
    val request = basicRequest
      .method(Method.POST, uri"$baseUrl/api/jobs/${jobGroup}/${jobName}")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth
      .auth
      .basic(username, password)
      .body(requestBody)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )
  }

  /** Returns the List of all registered Jobs with full information
    *
    * Expected answers: code 200 : Seq[JobInformation] () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def jobsList(bearerToken: String, username: String, password: String)(
  ): Request[Either[ResponseException[String, Exception], Seq[JobInformation]], Any] = {
    val request = basicRequest
      .method(Method.GET, uri"$baseUrl/api/jobs")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth
      .auth
      .basic(username, password)
      .response(asJson[Seq[JobInformation]])
  }

  /** Returns the List of possible job classes
    *
    * Expected answers: code 200 : Seq[String] () code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def possibleJobsList(bearerToken: String, username: String, password: String)(
  ): Request[Either[ResponseException[String, Exception], Seq[String]], Any] = {
    val request = basicRequest
      .method(Method.GET, uri"$baseUrl/api/jobs/classes")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth
      .auth
      .basic(username, password)
      .response(asJson[Seq[String]])
  }

  /** Register an Job and return the JobInformation with next schedule information
    *
    * Expected answers: code 200 : JobInformation () code 400 : String (Invalid value for: body) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param jobConfig
    */
  def registerJob(bearerToken: String, username: String, password: String)(
    jobConfig: JobConfig
  ): Request[Either[ResponseException[String, Exception], JobInformation], Any] = {
    val request = basicRequest
      .method(Method.PUT, uri"$baseUrl/api/jobs")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth
      .auth
      .basic(username, password)
      .body(jobConfig)
      .response(asJson[JobInformation])
  }

  /** Register an Trigger to schedule a Job only one time.
    *
    * Expected answers: code 204 : (Trigger added) code 400 : String (Invalid value for: body) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param triggerConfig
    */
  def registerTrigger(bearerToken: String, username: String, password: String)(
    triggerConfig: TriggerConfig
  ): Request[Either[ResponseException[String, Exception], Unit], Any] = {
    val request = basicRequest
      .method(Method.POST, uri"$baseUrl/api/jobs")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth
      .auth
      .basic(username, password)
      .body(triggerConfig)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )
  }

  /** Add Job and get JobInformation back
    *
    * Expected answers: code 200 : JobInformation () code 400 : String (Invalid value for: body) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param jobGroup
    *   Group Name of the Job
    * @param jobName
    *   Name of the Job
    * @param jobConfig
    */
  def updateJob(
    bearerToken: String,
    username: String,
    password: String
  )(jobGroup: String, jobName: String, jobConfig: JobConfig): Request[Either[ResponseException[String, Exception], JobInformation], Any] = {
    val request = basicRequest
      .method(Method.PATCH, uri"$baseUrl/api/jobs/${jobGroup}/${jobName}")
      .contentType("application/json")

    val withAuth = if (bearerToken.nonEmpty) request.auth.bearer(bearerToken) else request

    withAuth
      .auth
      .basic(username, password)
      .body(jobConfig)
      .response(asJson[JobInformation])
  }

}
