/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.api

import dev.quadstingray.quartz.manager.TestAdditions
import dev.quadstingray.quartz.manager.client.core.JsonSupport._
import dev.quadstingray.quartz.manager.client.model.JobConfig
import dev.quadstingray.quartz.manager.client.model.JobInformation
import sttp.client3._
import sttp.model.Method

object JobsApi {
  def apply(baseUrl: String = TestAdditions.testServerHost) = new JobsApi(baseUrl)
}

class JobsApi(baseUrl: String) {

  /** Delete Job and reload all Job Information
    *
    * Expected answers: code 204 : (Job deleted)
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param jobGroup
    *   Group Name of the Job
    * @param jobName
    *   Name of the Job
    */
  def deleteJob(username: String, password: String, bearerToken: Option[String])(
    jobGroup: String,
    jobName: String
  ): Request[Either[ResponseException[String, Exception], Unit], Any] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/api/jobs/${jobGroup}/${jobName}")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )

  /** Execute scheduled Job manually
    *
    * Expected answers: code 204 : (Job added to trigger) code 400 : String (Invalid value for: body)
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param jobGroup
    *   Group Name of the Job
    * @param jobName
    *   Name of the Job
    * @param requestBody
    *   Job Data map
    */
  def executeJob(
    username: String,
    password: String,
    bearerToken: Option[String]
  )(jobGroup: String, jobName: String, requestBody: Map[String, String]): Request[Either[ResponseException[String, Exception], Unit], Any] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/api/jobs/${jobGroup}/${jobName}")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .body(requestBody)
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )

  /** Returns the List of all registered Jobs with full information
    *
    * Expected answers: code 200 : Seq[JobInformation] ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def jobsList(username: String, password: String, bearerToken: Option[String])() =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/jobs")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .response(asJson[Seq[JobInformation]])

  /** Returns the List of possible job classes
    *
    * Expected answers: code 200 : Seq[String] ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def possibleJobsList(username: String, password: String, bearerToken: Option[String])(
  ): Request[Either[ResponseException[String, Exception], Seq[String]], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/jobs/classes")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .response(asJson[Seq[String]])

  /** Register an Job and return the JobInformation with next schedule information
    *
    * Expected answers: code 200 : JobInformation () code 400 : String (Invalid value for: body)
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param jobConfig
    */
  def registerJob(username: String, password: String, bearerToken: Option[String])(
    jobConfig: JobConfig
  ): Request[Either[ResponseException[String, Exception], JobInformation], Any] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/api/jobs")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .body(jobConfig)
      .response(asJson[JobInformation])

  /** Add Job and get JobInformation back
    *
    * Expected answers: code 200 : JobInformation () code 400 : String (Invalid value for: body)
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param jobGroup
    *   Group Name of the Job
    * @param jobName
    *   Name of the Job
    * @param jobConfig
    */
  def updateJob(
    username: String,
    password: String,
    bearerToken:  Option[String]
  )(jobGroup: String, jobName: String, jobConfig: JobConfig): Request[Either[ResponseException[String, Exception], JobInformation], Any] =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/api/jobs/${jobGroup}/${jobName}")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .body(jobConfig)
      .response(asJson[JobInformation])

}
