/** quartz-manager-api No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.quadstingray.quartz.manager.client.api

import dev.quadstingray.quartz.manager.TestAdditions
import sttp.client3._
import sttp.model.Method

object SchedulerApi {
  def apply(baseUrl: String = TestAdditions.testServerHost) = new SchedulerApi(baseUrl)
}

class SchedulerApi(baseUrl: String) {

  /** Shutdown the Quartz Scheduler
    *
    * Expected answers: code 204 : (Scheduler shutdown) code 400 : String (Invalid value for: query parameter waitForJobsToComplete) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    *
    * @param waitForJobsToComplete
    */
  def shutdownScheduler(username: String, password: String, bearerToken: Option[String])(waitForJobsToComplete: Option[Boolean] = None) =
    basicRequest
      .method(Method.POST, uri"$baseUrl/api/scheduler/shutdown?waitForJobsToComplete=${waitForJobsToComplete}")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )

  /** Standby the Quartz Scheduler
    *
    * Expected answers: code 204 : (Scheduler standby) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def standbyScheduler(username: String, password: String, bearerToken: Option[String])() =
    basicRequest
      .method(Method.POST, uri"$baseUrl/api/scheduler/standby")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )

  /** Start the Quartz Scheduler
    *
    * Expected answers: code 204 : (Scheduler started) code 0 : ErrorResponse ()
    *
    * Available security schemes: httpAuth1 (http) httpAuth (http)
    */
  def startScheduler(username: String, password: String, bearerToken: Option[String])() =
    basicRequest
      .method(Method.POST, uri"$baseUrl/api/scheduler/start")
      .contentType("application/json")
      .auth
      .basic(username, password)
      .auth
      .bearer(bearerToken.getOrElse("Bearer InvalidToken"))
      .response(
        asString.mapWithMetadata(
          ResponseAs.deserializeRightWithError(
            _ => Right(())
          )
        )
      )

}
